### ISSUE TITLE
Copy CI setup from https://github.com/awesomebytes/gentoo_prefix_ci_32b

### ISSUE THREAD

**Issue by awesomebytes** [awesomebytes/gentoo_prefix_ci_test#10]
Hey @tomkimsour could you pretty please do a PR to copy the CI setup from the 32b version of the repo here?

**Comment by tomkimsour** [comment]
I can do that. 
Isn't what was the pr you sended me something that fitted what you want ?

**Comment by awesomebytes** [comment]
Having a similar setup in both repos sounds easier to maintain to me :)
