### ISSUE TITLE
Unable to build gentoo prefix with docker

### ISSUE THREAD

**Issue by nikitamikhaylov** [awesomebytes/gentoo_prefix_ci_test#6]
Hello! I just tried to build gentoo prefix from this tutorial https://github.com/softbankrobotics-research/sbre_robot_ros_gentoo_prefix/tree/ros_kinetic with docker and I faced with some problems. 

```
Hmmmm, I was already afraid of this to happen.  Running
  /tmp/gentoo/bin/bash ./bootstrap-prefix.sh "/tmp/gentoo" stage3
somewhere failed :(  Details might be found in the build log:
  (no build logs found?!?)
I have no clue, really.  Please find friendly folks in #gentoo-prefix on
irc.gentoo.org, gentoo-alt@lists.gentoo.org mailing list, or file a bug
at bugs.gentoo.org under Gentoo/Alt, Prefix Support.  This is most
inconvenient, and it crushed my ego.  Sorry, I give up.
Should you want to give it a try, there is /tmp/gentoo/stage3.log
The command '/bin/sh -c LATEST_TREE_YES=1 TESTING_PV=latest ./bootstrap-prefix.sh ${EPREFIX} noninteractive stage3' returned a non-zero code: 1
```

I it is very interesting, because you CI also fails on stage3 . Please, help me  :cry:

**Comment by awesomebytes** [comment]
Hello,

Meanwhile the actual error (related to curl) gets fixed upstream you can
use any of the already bootstrapped Gentoo Prefix from the releases of this
repo. Seeing you want to use ROS, check the releases of my other repo
ros_overlay_on_gentoo_prefix, it's the same thing. There are 32bit versions
too.

I may take some days to re-stabilize the bootstraps (and sometimes it's not
up to me but I need someone to fix the actual problem in a library upstream
as I don't know how to fix it or don't have the time). But there are always
fully built images ready to use.

I haven't checked properly the repo you've linked (it's a surprise to me,
feels a bit like duplicating work). But if they are installing any extra SW
after ros_base, you can just do it yourself after extracting one of the
releases from my repos.

Good luck. Let me know if you need any extra help. I may lack some
documentation, but I don't really know where :)

**Comment by nikitamikhaylov** [comment]
Thank you very much! I will try to understand how to use prebuilt images with my tutorial.

**Comment by awesomebytes** [comment]
I've re-reported the bug: https://bugs.gentoo.org/708184

I gave it a go to try to find why it's happening but I had no luck. Hopefully someone will be able to take a look upstream soon.

**Comment by awesomebytes** [comment]
Note that I answered someone with a similar problem there: https://github.com/softbankrobotics-research/sbre_robot_ros_gentoo_prefix/issues/2 The explanation may be useful for you too.

**Comment by nikitamikhaylov** [comment]
Thank you! He is my teammate :smiley:

**Comment by awesomebytes** [comment]
All these issues have been fixed upstream and the CI is building again. So are the following images in:
* https://github.com/awesomebytes/ros_overlay_on_gentoo_prefix
* https://github.com/awesomebytes/ros_overlay_on_gentoo_prefix_32b
* https://github.com/awesomebytes/pepper_os
* https://github.com/awesomebytes/sbre_robot_ros_gentoo_prefix ( my fork from https://github.com/softbankrobotics-research/sbre_robot_ros_gentoo_prefix which has CI setup for nightly releases)

Closing the issue :)
